package com.weichi.erp.dao;

import com.weichi.erp.domain.GroupList;

public interface GroupListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_list
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    GroupList selectByPrimaryKey(Long id);
}