package com.weichi.erp.dao;

import com.weichi.erp.domain.Menu;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    Menu selectByPrimaryKey(Long id);
}