package com.weichi.erp.dao;

import com.weichi.erp.domain.OrderList;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    OrderList selectByPrimaryKey(Long id);
}