package com.weichi.erp.dao;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.weichi.erp.domain.SysPermission;

public interface SysPermissionMapper extends BaseMapper<SysPermission> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Thu Jun 07 15:18:45 CST 2018
     */
    SysPermission selectByPrimaryKey(Long id);
}