package com.weichi.erp.dao;

import com.baomidou.mybatisplus.plugins.pagination.Pagination;
import com.weichi.erp.domain.TBlog;
import com.weichi.erp.domain.TBlogExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int countByExample(TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int deleteByExample(TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int deleteByPrimaryKey(Integer blogId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int insert(TBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int insertSelective(TBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    List<TBlog> selectByExampleWithBLOBs(TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    List<TBlog> selectByExample(TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    TBlog selectByPrimaryKey(Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") TBlog record, @Param("example") TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TBlog record, @Param("example") TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int updateByExample(@Param("record") TBlog record, @Param("example") TBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int updateByPrimaryKeySelective(TBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    int updateByPrimaryKey(TBlog record);

    List<TBlog> getPage(Pagination page, TBlog param);
}