package com.weichi.erp.dao;

import com.weichi.erp.domain.UserGroup;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    UserGroup selectByPrimaryKey(Long id);
}