package com.weichi.erp.domain;

import java.util.Date;

public class GroupList extends SuperDomain<GroupList> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.id
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.group_name
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.group_owner_user_id
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private Long groupOwnerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.generate_purchase_list_time
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private Date generatePurchaseListTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.insert_username
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private String insertUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.insert_time
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.update_username
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private String updateUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.update_time
     *
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.id
     *
     * @return the value of group_list.id
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.id
     *
     * @param id the value for group_list.id
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.group_name
     *
     * @return the value of group_list.group_name
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.group_name
     *
     * @param groupName the value for group_list.group_name
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.group_owner_user_id
     *
     * @return the value of group_list.group_owner_user_id
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public Long getGroupOwnerUserId() {
        return groupOwnerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.group_owner_user_id
     *
     * @param groupOwnerUserId the value for group_list.group_owner_user_id
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setGroupOwnerUserId(Long groupOwnerUserId) {
        this.groupOwnerUserId = groupOwnerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.generate_purchase_list_time
     *
     * @return the value of group_list.generate_purchase_list_time
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public Date getGeneratePurchaseListTime() {
        return generatePurchaseListTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.generate_purchase_list_time
     *
     * @param generatePurchaseListTime the value for group_list.generate_purchase_list_time
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setGeneratePurchaseListTime(Date generatePurchaseListTime) {
        this.generatePurchaseListTime = generatePurchaseListTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.insert_username
     *
     * @return the value of group_list.insert_username
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public String getInsertUsername() {
        return insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.insert_username
     *
     * @param insertUsername the value for group_list.insert_username
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setInsertUsername(String insertUsername) {
        this.insertUsername = insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.insert_time
     *
     * @return the value of group_list.insert_time
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.insert_time
     *
     * @param insertTime the value for group_list.insert_time
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.update_username
     *
     * @return the value of group_list.update_username
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public String getUpdateUsername() {
        return updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.update_username
     *
     * @param updateUsername the value for group_list.update_username
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setUpdateUsername(String updateUsername) {
        this.updateUsername = updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.update_time
     *
     * @return the value of group_list.update_time
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.update_time
     *
     * @param updateTime the value for group_list.update_time
     * @mbggenerated Fri Jun 15 15:49:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}