package com.weichi.erp.domain;

import java.util.Date;

public class GroupList extends SuperDomain<GroupList> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.group_name
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.group_owner_user_id
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    private Long groupOwnerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_list.generate_purchase_list_time
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    private Date generatePurchaseListTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.group_name
     *
     * @return the value of group_list.group_name
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.group_name
     *
     * @param groupName the value for group_list.group_name
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.group_owner_user_id
     *
     * @return the value of group_list.group_owner_user_id
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    public Long getGroupOwnerUserId() {
        return groupOwnerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.group_owner_user_id
     *
     * @param groupOwnerUserId the value for group_list.group_owner_user_id
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    public void setGroupOwnerUserId(Long groupOwnerUserId) {
        this.groupOwnerUserId = groupOwnerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_list.generate_purchase_list_time
     *
     * @return the value of group_list.generate_purchase_list_time
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    public Date getGeneratePurchaseListTime() {
        return generatePurchaseListTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_list.generate_purchase_list_time
     *
     * @param generatePurchaseListTime the value for group_list.generate_purchase_list_time
     *
     * @mbggenerated Fri Jun 22 17:37:44 CST 2018
     */
    public void setGeneratePurchaseListTime(Date generatePurchaseListTime) {
        this.generatePurchaseListTime = generatePurchaseListTime;
    }
}