package com.weichi.erp.domain;

import java.util.Date;

public class Menu extends SuperDomain<Menu> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.dish_name
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    private String dishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.insert_username
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    private String insertUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.insert_time
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.update_username
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    private String updateUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.update_time
     *
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.dish_name
     *
     * @return the value of menu.dish_name
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public String getDishName() {
        return dishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.dish_name
     *
     * @param dishName the value for menu.dish_name
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public void setDishName(String dishName) {
        this.dishName = dishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.insert_username
     *
     * @return the value of menu.insert_username
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public String getInsertUsername() {
        return insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.insert_username
     *
     * @param insertUsername the value for menu.insert_username
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public void setInsertUsername(String insertUsername) {
        this.insertUsername = insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.insert_time
     *
     * @return the value of menu.insert_time
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.insert_time
     *
     * @param insertTime the value for menu.insert_time
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.update_username
     *
     * @return the value of menu.update_username
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public String getUpdateUsername() {
        return updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.update_username
     *
     * @param updateUsername the value for menu.update_username
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public void setUpdateUsername(String updateUsername) {
        this.updateUsername = updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.update_time
     *
     * @return the value of menu.update_time
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.update_time
     *
     * @param updateTime the value for menu.update_time
     * @mbggenerated Fri Jun 15 15:50:05 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}