package com.weichi.erp.domain;

public class OrderList extends SuperDomain<OrderList> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.user_id
     *
     * @mbggenerated Fri Jun 22 17:32:20 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.menu_id
     *
     * @mbggenerated Fri Jun 22 17:32:20 CST 2018
     */
    private Long menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.user_id
     *
     * @return the value of order_list.user_id
     *
     * @mbggenerated Fri Jun 22 17:32:20 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.user_id
     *
     * @param userId the value for order_list.user_id
     *
     * @mbggenerated Fri Jun 22 17:32:20 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.menu_id
     *
     * @return the value of order_list.menu_id
     *
     * @mbggenerated Fri Jun 22 17:32:20 CST 2018
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.menu_id
     *
     * @param menuId the value for order_list.menu_id
     *
     * @mbggenerated Fri Jun 22 17:32:20 CST 2018
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }
}