package com.weichi.erp.domain;

import java.util.Date;

public class OrderList extends SuperDomain<OrderList> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.id
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.user_id
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.menu_id
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.insert_username
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private String insertUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.insert_time
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.update_username
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private String updateUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.update_time
     *
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.id
     *
     * @return the value of order_list.id
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.id
     *
     * @param id the value for order_list.id
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.user_id
     *
     * @return the value of order_list.user_id
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.user_id
     *
     * @param userId the value for order_list.user_id
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.menu_id
     *
     * @return the value of order_list.menu_id
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.menu_id
     *
     * @param menuId the value for order_list.menu_id
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.insert_username
     *
     * @return the value of order_list.insert_username
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public String getInsertUsername() {
        return insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.insert_username
     *
     * @param insertUsername the value for order_list.insert_username
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setInsertUsername(String insertUsername) {
        this.insertUsername = insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.insert_time
     *
     * @return the value of order_list.insert_time
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.insert_time
     *
     * @param insertTime the value for order_list.insert_time
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.update_username
     *
     * @return the value of order_list.update_username
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public String getUpdateUsername() {
        return updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.update_username
     *
     * @param updateUsername the value for order_list.update_username
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setUpdateUsername(String updateUsername) {
        this.updateUsername = updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.update_time
     *
     * @return the value of order_list.update_time
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.update_time
     *
     * @param updateTime the value for order_list.update_time
     * @mbggenerated Fri Jun 15 15:53:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}