package com.weichi.erp.domain;

public class TBlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_id
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_title
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.user_id
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_content
     *
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_id
     *
     * @return the value of t_blog.blog_id
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_id
     *
     * @param blogId the value for t_blog.blog_id
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_title
     *
     * @return the value of t_blog.blog_title
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_title
     *
     * @param blogTitle the value for t_blog.blog_title
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.user_id
     *
     * @return the value of t_blog.user_id
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.user_id
     *
     * @param userId the value for t_blog.user_id
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_content
     *
     * @return the value of t_blog.blog_content
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_content
     *
     * @param blogContent the value for t_blog.blog_content
     * @mbggenerated Wed May 23 10:18:35 CST 2018
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
}