package com.weichi.erp.domain;

import java.util.Date;

public class UserGroup extends SuperDomain<UserGroup> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.id
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_id
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.group_id
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.group_role
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private String groupRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.insert_username
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private String insertUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.insert_time
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.update_username
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private String updateUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.update_time
     *
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.id
     *
     * @return the value of user_group.id
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.id
     *
     * @param id the value for user_group.id
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_id
     *
     * @return the value of user_group.user_id
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_id
     *
     * @param userId the value for user_group.user_id
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.group_id
     *
     * @return the value of user_group.group_id
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.group_id
     *
     * @param groupId the value for user_group.group_id
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.group_role
     *
     * @return the value of user_group.group_role
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public String getGroupRole() {
        return groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.group_role
     *
     * @param groupRole the value for user_group.group_role
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setGroupRole(String groupRole) {
        this.groupRole = groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.insert_username
     *
     * @return the value of user_group.insert_username
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public String getInsertUsername() {
        return insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.insert_username
     *
     * @param insertUsername the value for user_group.insert_username
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setInsertUsername(String insertUsername) {
        this.insertUsername = insertUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.insert_time
     *
     * @return the value of user_group.insert_time
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.insert_time
     *
     * @param insertTime the value for user_group.insert_time
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.update_username
     *
     * @return the value of user_group.update_username
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public String getUpdateUsername() {
        return updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.update_username
     *
     * @param updateUsername the value for user_group.update_username
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setUpdateUsername(String updateUsername) {
        this.updateUsername = updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.update_time
     *
     * @return the value of user_group.update_time
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.update_time
     *
     * @param updateTime the value for user_group.update_time
     * @mbggenerated Fri Jun 15 15:49:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}